[package]
name = "gaussian-signal-generation"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.6"
rand = "0.8.5"
regex = "1.10.4"
